### ISSUE TITLE
Projection RT missing of "3DPW in SMPLX format data"

### ISSUE THREAD

**Issue by Wei-Chen-hub** [pixelite1201/BEDLAM#37]
Hi, i have downloaded "3dpw_train_smplx.npz" from the website and have a few questions, I would much appreciate your kind help!

1. How is the smplx annotation generated?
2. It seems like an intrinsics projection as i didn't find anything related to extrinsics, but during projection I found the coordinate range of vertices is extremely large (-2924026.5 to 11260771.0), seems there's missing RT. Could you share a piece of projection code (the current one in repo generates the above result) or how 3dpw data is processed?

Thank you very much for helping!

**Comment by yufu-wang** [comment]
Hi, thank you for providing the smplx version for 3DPW!
However, as the comment above, the provided `"smplx_trans"` is in the world coordinate. The converted annotation does not include the cam_poses. As a result, we cannot infer the smplx mesh's postion wrt to the camera (full image), neither can we reproject the mesh to get 2D keypoints (in full image). 
I tried to pair the original cam_poses with your new annotation, but it's difficult because it's not 1-to-1. 
Could you provide a version where cam_poses from the originals is included?
Thank you,
Yufu
