### ISSUE TITLE
Question about the shape of  body shape paramerter

### ISSUE THREAD

**Issue by nguyenquivinhquang** [pixelite1201/BEDLAM#54]
Hi there,

I have a question about the body shape (betas). When I print the shape from `annot_x['shape'].shape` for the 6fps version, I see that the shape is `frames x 11`. However, when I run df_full_body.py to get the full 30fps version, the shape I get is only `frames x 10.` How can I obtain the shape `frames x 11` from df_full_body.py?

Thank you.

**Comment by nguyenquivinhquang** [comment]
I also tried visualising the output from df_full_body.py and observed the projected mesh relatively higher than the person in the image. Could you help me with this problem?
![0_Usersseq_000000_00001](https://github.com/user-attachments/assets/aaec01c3-1f0b-4ee0-b52d-b3bf1377cdd0)

**Comment by pixelite1201** [comment]
Hello,
Ground truth bodies in BEDLAM are gendered i.e. male and female with 10 betas. For training our model, we need neutral bodies so we fitted SMPL-X neutral bodies to gendered bodies using 11 betas. If you are using gendered bodies, 10 is the correct number of betas used.
Also, for your rendering it seems you are using wrong gender. If you are using gendered bodies for rendering instead of neutral ones, please modify the gender parameter in df_full_body.py
