### ISSUE TITLE
Possibility to download a subset

### ISSUE THREAD

**Issue by YuxuanSnow** [pixelite1201/BEDLAM#8]
Hi!

great work! Congratulate!

I wonder if we can download the paired training data (images, masks, depth maps) in small subsets? Downloading directly the whole data (6TB) requires a lot of disk space, which is limited in our setting.

Thanks!

**Comment by tpsmpi** [comment]
The 30fps data (images, masks, depth) download script release (`be_imagedata_download.zip`) contains config file `b0.txt` which specifies which subsets will be downloaded. You can remove unwanted entries to reduce download size.

Also the `png ` and `depth` subsets are broken up in 5 tar archives. You can change download script to only download first instead of all five (see `archive_ids`).

**Comment by YuxuanSnow** [comment]
Many thanks for the answer!
